---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

workspace:
  base: /maven/

steps:
- name: build
  image: arm32v7/maven:3.6-jdk-11-slim
  volumes:
  - name: maven-config
    path: /root/.m2
  commands:
  - mvn -B deploy -DaltDeploymentRepository=perfectable-snapshots::default::https://maven.perfectable.org/libs-snapshot-local
- name: cleanup-snapshots
  image: arm32v7/bash:5.0
  volumes:
  - name: maven-config
    path: /root/.m2
  commands:
  - rm -rf /root/.m2/repository/**/*-SNAPSHOT.*
  - rm -rf /root/.m2/repository/**/*.lastUpdated
  when:
    status:
    - success
    - failure

volumes:
- name: maven-config
  host:
    path: /site/build/m2

trigger:
  branch:
  - master
