---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

workspace:
  base: /root/maven

clone:
  disable: true

steps:
- name: clone
  image: images.perfectable.org/git-arm32v7:2.13.1-2.26.2-r0
  commands:
    - git clone $DRONE_GIT_HTTP_URL .
    - git checkout $DRONE_COMMIT
- name: build
  image: arm32v7/maven:3.6-jdk-11-slim
  volumes:
  - name: maven-config
    path: /m2
  commands:
  - mvn -B deploy -s /m2/settings.xml -DaltDeploymentRepository=perfectable-snapshots::default::https://maven.perfectable.org/libs-snapshot-local
- name: cleanup-snapshots
  image: arm32v7/bash:5.0
  volumes:
  - name: maven-config
    path: /m2
  commands:
  - rm -rf /m2/repository/**/*-SNAPSHOT.*
  - rm -rf /m2/repository/**/*.lastUpdated
  when:
    status:
    - success
    - failure

volumes:
- name: maven-config
  host:
    path: /site/build/m2

trigger:
  event:
  - push
